=== cromulencellc/chess-aces/phase_3/eval/kiaora/challenge/DikuMUD3/unit_tests/json_configs/schema_config_hashes.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "description": "Precomputed hashes for zone and def compiled files",
    "title": "Hash file config",
    "properties": {
        "name": {
            "description": "Descriptive name of the config file",
            "type": "string"
        },
        "relative_path": {
            "description": "Relative path from top of the source project to directory containing source files",
            "type": "string"
        },
        "new_file_check": {
            "description": "Parameters for discovering new files",
            "type": "object",
            "properties": {
                "source_extension": {
                    "description": "File extension used for source files eg '.zon'",
                    "type": "string"
                },
                "files_to_skip": {
                    "description": "List of files to exclude from new file check",
                    "type": "array",
                    "items": {
                        "description": "Filename (it will have project root + relative path added to the name",
                        "type": "string"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                },
                "output_extensions": {
                    "description": "List of output extensions from compiling a source file",
                    "type": "array",
                    "items": {
                        "description": "File extension used for source files eg '.data'",
                        "type": "string"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                }
            },
            "required": [
                "source_extension",
                "files_to_skip",
                "output_extensions"
            ]
        },
        "files": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "source_file": {
                            "description": "Filename and pre-calculated sha512 for the source file",
                            "type": "object",
                            "properties": {
                                "filename": {
                                    "description": "Filename (it will have project root + relative path added to the name",
                                    "type": "string"
                                },
                                "sha512": {
                                    "description": "Hex string of sha512 checksum",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "filename",
                                "sha512"
                            ]
                        },
                        "output": {
                            "description": "Filename(s) and pre-calculated sha512(s) created by source file",
                            "type": "array",
                            "items": {
                                "description": "An output file and pre-calculated sha512 hash of it",
                                "type": "object",
                                "properties": {
                                    "filename": {
                                        "description": "Filename (it will have project root + relative path added to the name",
                                        "type": "string"
                                    },
                                    "sha512": {
                                        "description": "Hex string of sha512 checksum",
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "filename",
                                    "sha512"
                                ]
                            }
                        }
                    },
                    "required": [
                        "source_file",
                        "output"
                    ]
                }
            ]
        }
    },
    "required": [
        "name",
        "relative_path",
        "new_file_check",
        "files"
    ]
}

=== cromulencellc/chess-aces/phase_3/eval/kiaora/challenge/DikuMUD3/unit_tests/json_configs/color_file_hashes.json
{
    "name": "etc Directory Files",
    "relative_path": "vme/etc/",
    "new_file_check": {
        "source_extension": ".def",
        "files_to_skip": [
            "abilities.dat",
            "abilities.def",
            "commands.dat",
            "commands.def",
            "professions.dat",
            "professions.def",
            "races.dat",
            "races.def",
            "sector.dat",
            "sector.def",
            "spells.dat",
            "spells.def",
            "weapons.dat",
            "weapons.def"
        ],
        "output_extensions": [
            ".dat"
        ]
    },
    "files": [
        {
            "source_file": {
                "filename": "color.def",
                "sha512": "b64d60cec255482c434c3727849dfc975abc8588bb0aca4dc1080f3eaae21781db21e026535789bd537bc08c1f0d6b33db7244e6ca24b08da43ae1ce2bd2cee2"
            },
            "output": [
                {
                    "filename": "color.dat",
                    "sha512": "986c2e8de3465251f81b30a907f01972f3bcee94161014cfd2e84c5722b550d26da6db084bd14c4effd5770873001b6b5b78d76858f88bd9c84b6aeab9daa1ef"
                }
            ]
        }
    ]
}
